### ISSUE TITLE
Removal of Broker List breaks dependancies

### ISSUE THREAD

**Issue by alexbkx** [uber-go/kafka-client#61]
_BrokerList_ has been [deprecated](https://github.com/uber-go/kafka-client/commit/cd5a6fca0a4eba60cdcd019c7060977e48628d26) in uber-go/kafka-client, breaking dependancies in uber/cadence (kafkaClient.go)

**Comment by georgeteo** [comment]
Per the rules of [semver](https://semver.org/), "Major version zero (`0.y.z`) is for initial development. Anything may change at any time. The public API should not be considered stable." We make an additional guarantee that during development phase (`0.MINOR.PATCH`), API stability is guaranteed at the `PATCH` level but not the `MINOR` level. Cadence should pin `~0.1.7` instead of `^0.1.7`.
